同步代码中异常使用 try/catch/finally 处理

```
function toUppercase(string) {
  if (typeof string !== "string") {
    throw TypeError("参数类型需要是 string 的");
  }

  return string.toUpperCase();
}

try {
  toUppercase(4);
} catch (error) {
  console.error(error.message);
} finally {
}

```
