可以使用 try catch 捕获异步操作当中的错误，并做处理

可以统一的在进入路由的时候做错误处理
```
// 在所有路由操作之前写
router.use(async (ctx, next) => {
	try{
		await next();
	}catch(e){
	}
});
```
这用所有的操作都是 next，不管哪一步操作出错误了都能捕获到，并进行统一处理
如果在 next 做了错误处理，这里的统一处理就不会执行，这样做的好处就是有明确的错误处理就使用明确的处理，没有的话就统一处理

统一处理可以在路由上做，也可以在 server 上做，方法是一样的
